name: Packaging

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: APT Update
      run: sudo apt update
    - name: Install system dependencies
      run: sudo apt install libwebkit2gtk-4.0-dev libgtk-3-dev libappindicator3-dev libasound2
    - name: Build
      run: cargo build --verbose --release
    - name: Archive build
      uses: actions/upload-artifact@v3
      with:
        name: ubuntu-build
        path: target/release/vocalize
      
  build-windows:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install msvc target
      run: rustup target add x86_64-pc-windows-msvc
    - name: Install xwin
      run: cargo install cargo-xwin
    - name: Build
      run: cargo xwin build --verbose --release --target x86_64-pc-windows-msvc
    - name: Archive build
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: target/x86_64-pc-windows-msvc/release/vocalize.exe
